import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";



export const metadata: Metadata = {
  title: "JSON-PLACEHOLDER-Api-14",
  description: "Generated by ghulam shabbir",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased bg-yellow-300/25`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
